title: Fusion Conclusion
description: "Staging (GitHub Pages) during migration from Ghost."
theme: minima

url: "https://dan-ftp.github.io"
baseurl: "/fusion-conclusion"
permalink: /:title/

timezone: America/New_York

plugins:
  - jekyll-feed
  - jekyll-sitemap
